### ISSUE TITLE
TypeError: Bad argument after login attempt

### ISSUE THREAD

**Issue by Dxhs** [Alex-Rose/fb-messenger-cli#110]
Facebook credentials:
    Email: foobar
    Password: foobar
    Attempting login...
    internal/child_process.js:294
    var err = this._handle.spawn(options);
                         ^
    
    TypeError: Bad argument
        at ChildProcess.spawn (internal/child_process.js:294:26)
        at exports.spawn (child_process.js:378:9)
        at new Login.run_cmd (/usr/local/lib/node_modules/fb-messenger-cli/scripts/login.js:54:17)
        at Login.execute (/usr/local/lib/node_modules/fb-messenger-cli/scripts/login.js:20:13)
        at executeCompleteLogin (/usr/local/lib/node_modules/fb-messenger-cli/cli.js:12:11)
        at launchApp (/usr/local/lib/node_modules/fb-messenger-cli/cli.js:47:7)
        at crypt.load (/usr/local/lib/node_modules/fb-messenger-cli/cli.js:40:16)
        at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/fb-messenger-cli/scripts    /crypt.js:45:11)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

OS: Linux Mint 18.2 Sonya x86_64
Model: XPS 15 9560
Kernel: 4.8.0-53-generic
node version: 7.10.1

**Comment by Dxhs** [comment]
Today the error message is gone. Prob fixed by system update
