### ISSUE TITLE
TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by sajattack** [Alex-Rose/fb-messenger-cli#116]
```
Login verification failed: No saved profile, please login
Facebook credentials:
Email: sajattack@gmail.com
Password: ********
Attempting login...
child_process.js:381
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at exports.spawn (child_process.js:488:38)
    at new Login.run_cmd (/usr/lib/node_modules/fb-messenger-cli/scripts/login.js:54:17)
    at Login.execute (/usr/lib/node_modules/fb-messenger-cli/scripts/login.js:20:13)
    at executeCompleteLogin (/usr/lib/node_modules/fb-messenger-cli/cli.js:12:11)
    at launchApp (/usr/lib/node_modules/fb-messenger-cli/cli.js:47:7)
    at crypt.load (/usr/lib/node_modules/fb-messenger-cli/cli.js:40:16)
    at ReadFileContext.fs.readFile [as callback] (/usr/lib/node_modules/fb-messenger-cli/scripts/crypt.js:45:11)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:421:13)
[paul@P50-Arch ~]$
```

**Comment by sajattack** [comment]
nevermind it was because of an install flag I used

**Comment by msawaie** [comment]
I'm having the same issue...how did you fix it?

**Comment by NilsDackeLever** [comment]
Same problem here.
