### ISSUE TITLE
Exception "SyntaxError: Unexpected token < in JSON at position 0" when attempting to select a conversation

### ISSUE THREAD

**Issue by toadhats** [Alex-Rose/fb-messenger-cli#124]
As of today I'm no longer able to use the app - it starts and signs in without difficulty, but i'm not able to select a conversation.

Full output:
```
Select conversation :
> 0
undefined:1
<title>Messenger | Page Not Found</title><link rel="shortcut icon" href="https://static.xx.fbcdn.net/rsrc.php/y7/r/O6n_HQxozp9.ico" /><div style="display: flex; align-items: center;
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\*****\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:240:25)
    at Request.self.callback (C:\Users\*****\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
```

**Comment by toadhats** [comment]
I forgot i had not updated the app in a while, so I did that. After launching again and providing login 
details, i saw some errors which I unfortunately lost and cannot reproduce, but the app launched ok and I got to the conversation select menu. Upon trying to select a conversation, i got a similar exception to last time:

```
Select conversation :
> 0
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\jwarner\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:244:25)
    at Request.self.callback (C:\Users\jwarner\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\jwarner\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (C:\Users\jwarner\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
```

**Comment by janfitz** [comment]
I have the same problem, the same error.

**Comment by SektorsT** [comment]
I've got the same problem. Also noticed that when I run "> /logout" it exits but it doesn't ask for e-mails and pwd next time I start it. I guess credentials are not flushed.
