### ISSUE TITLE
Error happened getting resource: Messages Unavailable

### ISSUE THREAD

**Issue by thinkedem** [Alex-Rose/fb-messenger-cli#126]
When the app tries to fetch the conversations on launch, it shows the following error instead of the list of conversations:
```
Found error while fetching conversations. Error: Error happened getting resource. Inner message : Messages Unavailable
    at Messenger.parseRawBody (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:360:13)
    at Request.request.post [as _callback] (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:470:25)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

I did an npm rm && npm install to make sure there's no corrupted dependency, and at the first launch, on login, I got the following warning as well:
`(node:10170) Warning: Use Cipheriv for counter mode of aes-256-ctr`

(using node v8.9.1, npm v5.5.1)

**Comment by thinkedem** [comment]
- might have been a FB issue, now it passed to the conversation list.

**Comment by SamBergeron** [comment]
This is probably linked to #128 Should be fixed now.
