### ISSUE TITLE
Cannot open conversation

### ISSUE THREAD

**Issue by wahidpro** [Alex-Rose/fb-messenger-cli#128]
This is the error message when I attempt to open a conversation.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\smartnote\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:244:25)
    at Request.self.callback (C:\Users\smartnote\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\smartnote\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (C:\Users\smartnote\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by AkshayPall** [comment]
+1

Right before the error, this is also printed
`undefined:1`

**Comment by enmaku** [comment]
Similar issue, slightly different error message. Looks like some resource this client had hardcoded has moved perhaps?

```
undefined:1
<title>Messenger | Page Not Found</title><link rel="shortcut icon" href="https://static.xx.fbcdn.net/rsrc.php/y7/r/O6n_HQxozp9.ico" /><div style="display: flex; align-items: center;
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:283:25)
    at Request.self.callback (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1085:12)
    at Gunzip.g (events.js:292:16)
```

**Comment by Alex-Rose** [comment]
That sounds just like a bug I fixed yesterday where the old URL is now returning a 404. You can try to pull the lastest changes from master to see if it's fixed. I'll validate this is the same issue once I get to my computer.

**Comment by wahidpro** [comment]
It is not fixed, same bug appears.

**Comment by lukcioj** [comment]
I tried the fix on the latest master and it's a little bit better because there is no crash after selecting a conversation. However later I get following error when trying to use /r flag:

`/Users/xxx/Development/fb-messenger-cli/scripts/interactive.js:154
    atts[attsNo] = a.preview.uri;
                             ^

TypeError: Cannot read property 'uri' of undefined
    at renderMessage (/Users/xxx/Development/fb-messenger-cli/scripts/interactive.js:154:30)
    at printMessages (/Users/xxx/Development/fb-messenger-cli/scripts/interactive.js:203:17)
    at messenger.getMessagesGraphQl (/Users/xxx/Development/fb-messenger-cli/scripts/interactive.js:217:9)
    at Request._callback (/Users/xxx/Development/fb-messenger-cli/scripts/messenger.js:353:14)
    at Request.self.callback (/Users/xxx/Development/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/xxx/Development/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
`

I think it happens when there is some kind of attachment (image) in the conversation.

**Comment by velocyno** [comment]
Same issue.
Conversation contains gifs.
Tried to open conversation without gifs - same error.


```
Select conversation :
> 0
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:244:25)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

```

**Comment by Alex-Rose** [comment]
Sounds like there are multiple regressions with recent FB changes. I'll get to it

**Comment by insideClaw** [comment]
Same issue, fresh after installing. Running Mocha on regression.js shows a bunch of errors that seem to revolve around:
```
TypeError: Crypt.getInstance is not a function
TypeError: Cannot read property 'getMessages' of undefined 
```
Whereas the last one happens on multiple properties. A total of 0 passing, 12 failing.

Seems like a really well made software, excited for when I can use it :)

**Comment by WangElectronics** [comment]
Same issue here. Just installed this and tried.

`undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:244:25)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Gunzip.g (events.js:291:16)`

**Comment by xedret** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/5193544/33848518-dae702fc-de62-11e7-8801-c0f8a9980644.png)

**Comment by SamBergeron** [comment]
Yo people! @Alex-Rose did indeed fix this in f4fb8fa78bb9c9788e593a4496d142524fd0882d 
This has now been pushed in version 1.8.3 if you're running it from npm. Please go ahead an update.
Let us know if any of the other endpoints are failing.
Cheers.

**Comment by insideClaw** [comment]
Can confirm updating with npm to the new version fixes it. Thanks Alex!

**Comment by enmaku** [comment]
Just updated from npm, still can't select a conversation.

```
Select conversation :
> 1
undefined:1
<title>Messenger | Page Not Found</title><link rel="shortcut icon" href="https://static.xx.fbcdn.net/rsrc.php/y7/r/O6n_HQxozp9.ico" /><div style="display: flex; align-items: center;
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:283:25)
    at Request.self.callback (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\Users\dperry.GOLDENGAMINGINC\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1085:12)
    at Gunzip.g (events.js:292:16)
```

**Comment by Alex-Rose** [comment]
That looks oddly like the issue we just fixed... Let met check one more time

**Comment by WangElectronics** [comment]
Works on OSX terminal now as well! Thanx! :dancing_men:
