### ISSUE TITLE
Cannot open message thread after login ;-(

### ISSUE THREAD

**Issue by nascarsayan** [Alex-Rose/fb-messenger-cli#129]
Cannot open conversation thread after logging into the app. 
```
Select conversation :
> 3
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/home/nascarsayan/.npm-packages/lib/node_modules/fb-messenger-cli/scripts/messenger.js:244:25)
    at Request.self.callback (/home/nascarsayan/.npm-packages/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/nascarsayan/.npm-packages/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/home/nascarsayan/.npm-packages/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Gunzip.g (events.js:292:16)
```
![image](https://user-images.githubusercontent.com/17731151/33879762-679e6db4-df55-11e7-9e9b-8a40a4433cd6.png)

I have installed the latest version of `fb-messenger-cli` using npm. Any suggestions?

**Comment by udayb2014** [comment]
looks like #128

**Comment by SamBergeron** [comment]
This is indeed #128
