### ISSUE TITLE
Can't log in since today.

### ISSUE THREAD

**Issue by WangElectronics** [Alex-Rose/fb-messenger-cli#133]
>/usr/local/lib/node_modules/fb-messenger-cli/node_modules/form-data/lib/form_data.js:226
  } else if (options.filename || value.name || value.path) {
                                      ^

>TypeError:` Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/form-data/lib/form_data.js:226:39)
    at FormData._multiPartHeader (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/form-data/lib/form_data.js:177:33)
    at FormData.append (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/form-data/lib/form_data.js:70:21)
    at appendFormValue (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:323:21)
    at Request.init (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:334:11)
    at new Request (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:128:8)
    at request (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/index.js:53:10)
    at Function.post (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/index.js:61:12)
    at Messenger.getFriends (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:513:11)
    at crypt.load (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:518:17)

**Comment by SamBergeron** [comment]
Did you try something different? It still seems to work here. 
You can try removing the `.kryptonite` file in the project root to force a full reload.

**Comment by SamBergeron** [comment]
This is resolved along with #136
