### ISSUE TITLE
"file" argument must be a non-empty string

### ISSUE THREAD

**Issue by msawaie** [Alex-Rose/fb-messenger-cli#137]
Login verification failed: No saved profile, please login
Facebook credentials:
Email: dfsr
Password: *****
Attempting login...
child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at new Login.run_cmd (/Users/msawaie/Downloads/fb-messenger-cli/scripts/login.js:59:19)
    at Login.execute (/Users/msawaie/Downloads/fb-messenger-cli/scripts/login.js:23:15)
    at executeCompleteLogin (/Users/msawaie/Downloads/fb-messenger-cli/cli.js:12:15)
    at launchApp (/Users/msawaie/Downloads/fb-messenger-cli/cli.js:47:13)
    at crypt.load (/Users/msawaie/Downloads/fb-messenger-cli/cli.js:40:24)
    at ReadFileContext.fs.readFile [as callback] (/Users/msawaie/Downloads/fb-messenger-cli/scripts/crypt.js:45:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)

**Comment by Jugulaire** [comment]
Same for me

**Comment by SamBergeron** [comment]
Hey guys. We've just published version 2.0 on both NPM and here.
Version 2 uses Google chrome's Puppeteer instead of PhantomJS for the login. This solves a lot of headaches. Please download the latest version, install all the dependencies and you should be all set

**Comment by SamBergeron** [comment]
This is confirmed as closed since 2.0
