### ISSUE TITLE
Found error while fetching conversations. TypeError: Cannot read property 'green' of undefined

### ISSUE THREAD

**Issue by ditchfieldcaleb** [Alex-Rose/fb-messenger-cli#149]
After successfully logging in, 8 conversations load, and then instantly, the below errors appears. 

```
Found error while fetching conversations. TypeError: Cannot read property 'green' of undefined
    at Listeners.printThreadSnippet (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/scripts/listeners.js:30:60)
    at messenger.getThreads (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/scripts/listeners.js:64:22)
    at Request.request.post [as _callback] (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/scripts/messenger.js:480:17)
    at Request.self.callback (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at Gunzip.<anonymous> (/home/caleb/.nvm/versions/node/v9.5.0/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at Gunzip.emit (events.js:165:20)
Could not properly initialize conversation listener. 
Reason: TypeError: Cannot read property 'green' of undefined. 
Exiting...

```
```
~ » which node                                                    caleb@stealth
/home/caleb/.nvm/versions/node/v9.5.0/bin/node
```

```
~ » which fb-messenger-cli                                        caleb@stealth
/home/caleb/.nvm/versions/node/v9.5.0/bin/fb-messenger-cli

```

**Comment by SamBergeron** [comment]
Interesting, this would mean that the thread you have, "exists" but has no name. 
Do you know what the actual thread name is? If you go to messenger.com and look at the 8th conversation. What is it named?

Also... this is an easy fix but I would like to understand what is causing it :)

**Comment by SamBergeron** [comment]
I stumbled upon this really out of nowhere right after you posted the defect! It happened for me when I was trying to buy something and had a conversation with a seller. 
The conversation was marked neither as "GROUP" or "ONE-ON-ONE". Which caused this issue.
Thanks for pointing it out!
