### ISSUE TITLE
Can't login -- Error while fetching conversations. Error: Error happened getting resource

### ISSUE THREAD

**Issue by SeleniumK** [Alex-Rose/fb-messenger-cli#156]
Launching app...
Fetching conversations...
> Found error while fetching conversations. Error: Error happened getting resource. Inner message : Sorry, something went wrong
    at Messenger.parseRawBody (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:367:13)
    at Request.request.post.e [as _callback] (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:477:25)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Gunzip.g (events.js:291:16)

**Comment by SamBergeron** [comment]
Are you using the latest version? The line numbers don't see to match. 
This also looks like a parsing error, do you get this every time?

**Comment by BourAbdelhadi** [comment]
I have the same issue ? any idea ?

**Comment by SeleniumK** [comment]
Upgrading to latest version resolved this.
