### ISSUE TITLE
Found error while fetching conversations. TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by J-Z-K** [Alex-Rose/fb-messenger-cli#186]
#136 didn't help 

> Found error while fetching conversations. TypeError: Cannot read property 'length' of undefined
    at Messenger.saveParticipantsAsFriends (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:69:36)
    at Request.request.post [as _callback] (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:480:12)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by SamBergeron** [comment]
Hi @J-Z-K, it doesn't look like you're running the latest version of the app, as the error code doesn't line up in the app. A similar error has also been fixed in the past
You can just pull the latest version from npm
