### ISSUE TITLE
Error 404 during installation

### ISSUE THREAD

**Issue by lepidopteralady1781** [Alex-Rose/fb-messenger-cli#191]
Terminal Output:
`lepidopteralady@pop-os:~$ sudo su
root@pop-os:/home/lepidopteralady# npm install -g fb-messenter-cli
npm ERR! code E404
npm ERR! 404 Not Found: fb-messenter-cli@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-31T21_12_51_322Z-debug.log
`
Debug Log:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'fb-messenter-cli' ]
2 info using npm@5.8.0
3 info using node@v8.11.4
4 verbose npm-session 8eb1f625eea68e64
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/fb-messenter-cli 519ms
8 silly fetchPackageMetaData error for fb-messenter-cli@latest 404 Not Found: fb-messenter-cli@latest
9 verbose stack Error: 404 Not Found: fb-messenter-cli@latest
9 verbose stack     at fetch.then.res (/usr/share/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/lib/nodejs/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/nodejs/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/nodejs/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/nodejs/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/nodejs/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/nodejs/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/nodejs/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/lib/nodejs/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:810:20)
9 verbose stack     at tryOnImmediate (timers.js:768:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
10 verbose cwd /home/lepidopteralady
11 verbose Linux 4.18.0-13-generic
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "fb-messenter-cli"
13 verbose node v8.11.4
14 verbose npm  v5.8.0
15 error code E404
16 error 404 Not Found: fb-messenter-cli@latest
17 verbose exit [ 1, true ]
`
It looks like I'm getting a 404 when the installer goes to check the npm registry.

**Comment by rgamec** [comment]
You have a typo in your NPM install command, it's fb-**messenger**-cli not fb-**messenter**-cli.
