### ISSUE TITLE
Chats not refreshing automatically

### ISSUE THREAD

**Issue by blandre** [Alex-Rose/fb-messenger-cli#220]
Whenever I receive a new message, it doesn't automatically show, unless I manually refresh. The same happens when I send new messages, the '>' indicator doesn't show after I send the first time. Again, refreshing manually seems to work.

**Comment by Horites** [comment]
Im having the same exact problem

**Comment by j6k4m8** [comment]
I am running into the same issue. Some important diagnostics:
* messages still do send upon hitting <kbd>enter</kbd>
* new messages do not render in the thread

(Hope @Horites and @blandre will let me know if their experiences differ from this)

**Comment by wgehalo** [comment]
Same issue here.

Also might be worth noting Messer, a similar project, is having a similar issue. I suspect facebook updated their API which is causing this issue.

**Comment by Horites** [comment]
Hello @j6k4m8 
Yes, it seems like Im having the exact same problem as you are.
I do belive @wgehalo would be correct on the API issue.

**Comment by Toz3wm** [comment]
Same problem here. 
Anyone aware of a similar project that fixed this problem ?

**Comment by michondr** [comment]
joining you guys. discovered cli clients yeasterday and still didn't manage to make usable this one nor messer :smile:. 

also, this happens
```
> /search adama
/usr/lib/node_modules/fb-messenger-cli/lib/search.js:49
            return friend.name.toLowerCase().indexOf(searchString.toLowerCase()) !== -1;
                               ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at /usr/lib/node_modules/fb-messenger-cli/lib/search.js:49:32
    at Array.filter (<anonymous>)
    at Search.filterFriends (/usr/lib/node_modules/fb-messenger-cli/lib/search.js:48:38)
    at /usr/lib/node_modules/fb-messenger-cli/lib/search.js:42:18
```

**Comment by j6k4m8** [comment]
@michondr your second bug looks like it's solved here:
https://github.com/Alex-Rose/fb-messenger-cli/issues/193

- Delete the `.kryptonite` file 
- Make sure you're on the latest node versions

**Comment by B-greg** [comment]
I'm having the same problem. Did they have any progress on this issue?

**Comment by gcantieni** [comment]
yeah i've just taken to typing `/r` after every series of messages, not quite ideal but...beats opening the browser?

**Comment by j6k4m8** [comment]
Can you verify that adding a /r to typed messages remedies this issue? Can
others verify it works for them?

**Comment by blandre** [comment]
<del>I tried reinstalling and messed something up, so I'm currently relying on a docker version that is not even loading conversation lists
However, I remember being able to use /r to refresh conversations and it worked..</del>

Just tested it, and typing a /r after sending a message remedies the issue. However, it does not seem to refresh the messages after receiving a response.

**Comment by gregoryfenton** [comment]
Typing in the message, pressing Enter
then typing /r
works for me but typing /r constantly to check is a bit of a pain

**Comment by j6k4m8** [comment]
To help start to centralize this:

It looks like this code is responsible for handling the explicit refresh command with `/refresh` or `/r`:

https://github.com/Alex-Rose/fb-messenger-cli/blob/309d605fa3d2febd59a51f8e93e1512f2b17f497/lib/interactive.js#L431-L437

Might need some other eyes on this, but I believe this code is where the new incoming message triggers a thread refresh:

https://github.com/Alex-Rose/fb-messenger-cli/blob/309d605fa3d2febd59a51f8e93e1512f2b17f497/lib/interactive.js#L264-L267

Actual refresh here:

https://github.com/Alex-Rose/fb-messenger-cli/blob/309d605fa3d2febd59a51f8e93e1512f2b17f497/lib/interactive.js#L285

I can spend more time on this during the weekend, but hopefully this helps us start narrowing down where the bug lives.
