### ISSUE TITLE
Error in logout

### ISSUE THREAD

**Issue by newtonke** [Alex-Rose/fb-messenger-cli#224]
Select conversation :
> /logout
readline.js:1141
            throw err;
            ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:151:11)
    at Object.unlink (fs.js:1057:14)
    at Crypt.flush (/usr/local/lib/node_modules/fb-messenger-cli/lib/crypt.js:64:12)
    at InteractiveCli.exit (/usr/local/lib/node_modules/fb-messenger-cli/lib/interactive.js:555:15)
    at InteractiveCli.handleCommands (/usr/local/lib/node_modules/fb-messenger-cli/lib/interactive.js:406:25)
    at Interface.InteractiveCli.handler (/usr/local/lib/node_modules/fb-messenger-cli/lib/interactive.js:466:21)
    at Interface.emit (events.js:321:20)
    at Interface._onLine (readline.js:327:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:997:14) {
  code: 'ERR_INVALID_CALLBACK'
}

**Comment by flokirr** [comment]
Happens on OSX as well.

**Comment by alansyue1020** [comment]
same error
`readline.js:1086
            throw err;
            ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.unlink (fs.js:943:14)
    at Crypt.flush (/Users/alansyue/.nvm/versions/node/v10.21.0/lib/node_modules/fb-messenger-cli/lib/crypt.js:64:12)
    at InteractiveCli.exit (/Users/alansyue/.nvm/versions/node/v10.21.0/lib/node_modules/fb-messenger-cli/lib/interactive.js:555:15)
    at InteractiveCli.handleCommands (/Users/alansyue/.nvm/versions/node/v10.21.0/lib/node_modules/fb-messenger-cli/lib/interactive.js:406:25)
    at Interface.InteractiveCli.handler (/Users/alansyue/.nvm/versions/node/v10.21.0/lib/node_modules/fb-messenger-cli/lib/interactive.js:466:21)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:937:14)`

**Comment by alansyue1020** [comment]
@newtonke @RRaadi @Alex-Rose 
I found that npm latest version was different from the github code.
npm latest version code had problem on crypt.js flush function,
```
fs.unlink(path.resolve(__dirname, '../', this.filename)
```
and it didn't have callback function

**Comment by AlanSyue** [comment]
@newtonke @RRaadi @Alex-Rose
There is some problems because 

latest version of NPM‘s code is different from GitHub’s code

There is no callback function in
```
fs.unlink(path.resolve(__dirname, '../', this.filename)
```
