### ISSUE TITLE
puppeteer@1.20.0 error

### ISSUE THREAD

**Issue by Ryjekk** [Alex-Rose/fb-messenger-cli#226]
hello guys, during install, I get this error : 
 Any clue why?
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: node install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/inuk/.npm/_logs/2020-04-03T10_23_55_057Z-debug.log
```

**Comment by anth-volk** [comment]
I, too, have had this issue on an up-to-date version of Manjaro Linux.

**Comment by jakewilliami** [comment]
I have this error too on my MBP running Mojave:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/fb-messenger-cli -> /usr/local/lib/node_modules/fb-messenger-cli/cli.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jakewilliami/.npm/_logs/2020-04-20T10_33_43_194Z-debug.log
```

**Comment by Mazurel** [comment]
For anyone still having this issue, just use:
`sudo npm install -g fb-messenger-cli --unsafe-perm=true`
it should fix `mkdir` problem (solution based on [this](https://github.com/puppeteer/puppeteer/issues/367#issuecomment-499315095)).

Also, you may have a problem with write permission in "/usr/lib/node_modules/fb-messenger-cli/" folder, in which case just use `chmod`.
For example: `sudo chmod a+rw /usr/lib/node_modules/fb-messenger-cli/`

**Comment by Nemesis77swe** [comment]
Still an issue, but @Mazurel workaround works fine..
