### ISSUE TITLE
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by ChristianPyth** [Alex-Rose/fb-messenger-cli#229]
`[sudo] password for christian: 
Login verification failed: Warning: Settings not found, saving default values
Facebook credentials:
Email: 
Password: 
Attempting login...
Fetching login cookie
Login verification failed: No saved profile, please login
Facebook credentials:
Email: 
Password: 
Attempting login...
Fetching login cookie
Settings have been saved
Browser resolved
Browser resolved
Waiting 20 seconds for login page
Waiting 20 seconds for login page
Error while logging in Error: Evaluation failed: Cookie not found. Cause unknown.
Error while logging in Error: Evaluation failed: Cookie not found. Cause unknown.
(node:25315) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Cookie not found. Cause unknown.
    at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at browser.pages.then.then.then.cookie (/usr/local/lib/node_modules/fb-messenger-cli/lib/login.js:150:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:25315) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25315) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Browser properly closed
Login verification failed: Error: Evaluation failed: Cookie not found. Cause unknown.
Exiting. Please try again.
`

Any fixes?

**Comment by nguyenngochoang** [comment]
I can't use this tool for a while, and as I remember... Facebook hasn't allowed user to login from anonymous sources anymore.
