### ISSUE TITLE
/groups command crash!

### ISSUE THREAD

**Issue by mortenskoett** [Alex-Rose/fb-messenger-cli#26]
Hello.

Great program you have written. Thanks for that!

I'm wondering if the following is a known bug or perhaps just on my specific system.
I have disabled two-step-verification to make the program accept my login. I'm on Fedora 25 with python3 and pip3 updated.

Whenever I give the /groups (or /group) command I get a crash and the following is printed:

    /usr/lib/node_modules/fb-messenger-cli/scripts/listeners.js:19
      for(var j = 0; j < thread.attachments.length; j++) {
                                       ^
    TypeError: Cannot read property 'length' of undefined
        at printThreadSnippet (/usr/lib/node_modules/fb-messenger-cli/scripts/listeners.js:19:40)
        at /usr/lib/node_modules/fb-messenger-cli/scripts/listeners.js:56:9
        at Request._callback (/usr/lib/node_modules/fb-messenger-cli/scripts/messenger.js:407:9)
        at Request.self.callback (/usr/lib/node_modules/fb-messenger-    cli/node_modules/request/request.js:186:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/usr/lib/node_modules/fb-messenger-    cli/node_modules/request/request.js:1081:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at Gunzip.<anonymous> (/usr/lib/node_modules/fb-messenger-   cli/node_modules/request/request.js:1001:12)

**Comment by SamBergeron** [comment]
Yup this is an issue with the latest pull request that we missed #24 , it's referenced here #25 . I'll have to look into it over the weekend. In the meantime you can build the previous version and group conversations should work fine.
