### ISSUE TITLE
Unable to show group messages

### ISSUE THREAD

**Issue by chpecson** [Alex-Rose/fb-messenger-cli#27]
An error occurs when you type /groups command:

C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\listeners.js:19
  for(var j = 0; j < thread.attachments.length; j++) {
                                       ^

TypeError: Cannot read property 'length' of undefined
    at printThreadSnippet (C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\listeners.js:19:40)
    at C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\listeners.js:56:9
    at Request._callback (C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\messenger.js:407:9)
    at Request.self.callback (C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\Users\chpecson\AppData\Roaming\npm\node_modules\fb-messenger-cli\node_modules\request\request.js:1001:12)

I hope this will error log will hep you in fixing the error.

**Comment by SamBergeron** [comment]
This was fixed in the last build! Check out #26!  You can re-install with npm.
