### ISSUE TITLE
Impossible to login 

### ISSUE THREAD

**Issue by rcspam** [Alex-Rose/fb-messenger-cli#28]
Hi,
Thanx for this app, but i would like to try it ;)
It is impossible to login, here is the output:

```
$ fb-messenger-cli
Can't find the .kryptonite file, we'll make a new one
Facebook credentials
prompt: email:  xxxxxxxxx@gmail.com
prompt: password:  
undefined:1
Blocked a frame with origin "https://www.facebook.com" from accessing a frame with origin https://www.messenger.com". Protocols, 
domains, and ports must match.
^

SyntaxError: Unexpected token B
    at Object.parse (native)
    at Socket.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/scripts/login.js:36:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

```

**Comment by SamBergeron** [comment]
This is weird, it seems PhantomJS is complaining about a redirect. Do you have a proxy or something special with your internet connect. 

I'll need some specifics if I can hope to reproduce this.

**Comment by SamBergeron** [comment]
Merging these into one common issue (#53)
