### ISSUE TITLE
Unexpected identifier on first run

### ISSUE THREAD

**Issue by rapidx** [Alex-Rose/fb-messenger-cli#56]
Hi there, 

After installing I get the following error on the first run- any ideas? 

```
/usr/local/lib/node_modules/fb-messenger-cli/scripts/login.js:30

          let trimmed = phantom.data.substring(phantom.data.indexOf('{'));
              ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/fb-messenger-cli/cli.js:4:15
    at Object.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/cli.js:100:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Many thanks!
M

**Comment by SamBergeron** [comment]
What version of node are you using? This looks like you're running something that doesn't support ES6.

**Comment by rapidx** [comment]
Hmm. I'm on ubuntu 14.04 nodejs v0.10.25 and npm v1.3.10..

**Comment by SamBergeron** [comment]
Yeah you'll need node >= 6.4.0. I should definitely add that to the package.json and the readme!
