### ISSUE TITLE
Cannot read property 'length' of undefined in listeners.js

### ISSUE THREAD

**Issue by schaefferp** [Alex-Rose/fb-messenger-cli#59]
Hi,

This is what I have when logging in with a fresh clone of the repo :

```
Password: **************
Warning: Errors caught in return data
Warning : settings not found, lets try to create default
Launching app...
Settings have been saved
> 
/home/pierre/fb-messenger-cli/scripts/listeners.js:33
    for (var i = 0; i < threads.length; ++i) {
                               ^

TypeError: Cannot read property 'length' of undefined
    at /home/pierre/fb-messenger-cli/scripts/listeners.js:33:32
    at Request._callback (/home/pierre/fb-messenger-cli/scripts/messenger.js:318:9)
    at Request.self.callback (/home/pierre/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pierre/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/home/pierre/node_modules/request/request.js:1091:12)
    at Gunzip.g (events.js:292:16)
```

Was working fine last week.
Thanks for your help ;)

**Comment by SamBergeron** [comment]
Hey I tried to repro this but I wasn't seeing anything. Can you tell me why you closed it? Found the culprit?

**Comment by schaefferp** [comment]
Hi !

Yes, sorry, actually it's a Facebook-side bug with ephemeral chats, so it
has nothing to do with fb-messenger-cli, sorry for not getting back to you
when closing the issue.
Actually, even in Facebook, chats didn't display, after archiving the
tainted conversation, everything's fine. I filed a bug to the Facebook team
as well.

Thanks for your work btw !

Cheers
Pierre

2017-06-07 17:35 GMT+02:00 Samuel Bergeron <notifications@github.com>:
