### ISSUE TITLE
Length of attachements is undefined, after recent update

### ISSUE THREAD

**Issue by piotryordanov** [Alex-Rose/fb-messenger-cli#66]
Hello again,

I did a fresh install of the app. After I log in and get the list of chats, I select the chat I want to go and I get this error:

```
/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:71
    for (var i = 0; i < message.attachments.length; i++) {
                                           ^

TypeError: Cannot read property 'length' of undefined
    at renderMessage (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:71:44)
    at printMessages (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:150:17)
    at messenger.getMessages (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:160:7)
    at Request._callback (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:260:9)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
```

It's werid cuz I didn't face it yesterday!

**Comment by janfitz** [comment]
I have the same Issue. It looks like a problem with messages contains attachments. Chat without any special attachment in latest messages works fine. Maybe is it causes by #63

**Comment by SamBergeron** [comment]
@janfitz it is in fact a problem with #63. Attachments aren't dealt with in the same way with the new GraphQl stuff they released, sorry I tested it too fast (goog catch Jan) 

btw, I'll need to roll out more changes in relation to them updating a lot of messenger.com clients to GraphQl, so keep doing the good work of checking my ass why I commit shitty code! Cheers 😆

**Comment by Smile4ever** [comment]
Is this fix already available as an update using npm? Because it still crashes for me using the latest version installed using npm.

**Comment by piotryordanov** [comment]
Yup. Any update would be nice. The npm version just won't work at all sadly :(

**Comment by piotryordanov** [comment]
Yup, it works. Thank you :)
