### ISSUE TITLE
Cannot read property 'length' of undefined in interactive.js

### ISSUE THREAD

**Issue by romainrichard** [Alex-Rose/fb-messenger-cli#68]
This is the error I got this morning while opening a conversation:
```
/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:71
    for (var i = 0; i < message.attachments.length; i++) {
                                           ^

TypeError: Cannot read property 'length' of undefined
    at renderMessage (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:71:44)
    at printMessages (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:150:17)
    at messenger.getMessages (/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:160:7)
    at Request._callback (/usr/local/lib/node_modules/fb-messenger-cli/scripts/messenger.js:260:9)
    at Request.self.callback (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
```

Since it worked fine earlier, I think the reason is because I sent a picture on Facebook. As a result, I'm not able to open any of the conversations. I tried sending a text message on Facebook in the conversation that had a picture (hoping that it would fix the issue), but this is still happening.

**Comment by SamBergeron** [comment]
This is the same as #68, it's an error with the old attachments now that I've pushed code for the new endpoints. It should be fixed in the latest clone of the repo, but I haven't pushed it to npm.

If you have anything else with this just post it in the other thread, thanks!
